#!/bin/sh

# If any command fails, exit immediately with that command's exit status
set -euxo pipefail

if ! cargo fmt -- --check
then
	echo "There are some code style issues."
	echo "Run cargo fmt first."
	exit 1
fi

if ! cargo clippy --all-targets -- -D warnings -D clippy::pedantic -D clippy::style -D clippy::restriction -A clippy::print_stdout -A clippy::missing_docs_in_private_items -A clippy::std_instead_of_core -A clippy::implicit_return
then
	echo "There are some clippy issues."
	exit 1
fi

if ! cargo test
then
	echo "There are some test issues."
	exit 1
fi

if ! cargo audit
then
	echo "There are some vulnerabilities."
	exit 1
fi

exit 0
